#!/bin/sh
# Function to add a given directory to the end of the path variable 
appendpath() {
    case ":$PATH:" in
    *:"$1":*) ;;
    *)
        PATH="${PATH:+$PATH:}$1"
        ;;
    esac
}

appendpath "$1"