#!/bin/sh
# Script to get the names of all shell functions which are exposed/sourced in the current shell session
getfunctionnames() {
    if command -v declare >/dev/null; then
        declare -f | awk -v RS='\n}\n' '/[^:cntrl::space:]*\(\)[:cntrl::space:]*/ {print $1}' | sed "/^_/D" | sed "s/[()]*/""/g" | sed "/[\[\]+(){}=%\;~$]/D" | sed "/function.*/D" | sed "/local.*/D" | sed "/^$/d" | sort -u
    elif command -v typeset >/dev/null; then
        typeset -f | awk -v RS='\n}\n' '/[^:cntrl::space:]*\(\)[:cntrl::space:]*/ {print $1}' | sed "/^_/D" | sed "s/[()]*/""/g" | sed "/[\[\]+(){}=%\;~$]/D" | sed "/function.*/D" | sed "/local.*/D" | sed "/^$/d" | sort -u
    else
        echo "This command is incompatible with this shell! Use more featureful shell like ksh, bash, zsh, etc."
        return 1
    fi
}