#!/bin/sh
# Script to get, split, and output the directories listed in the PATH variable
getpathdirs() {
    in="$PATH"
    while [ "$in" != "$currentelement" ]; do
        # Extract the first path (all text up to the first colon)
        currentelement=${in%%:*}
        # Delete the pulled path from the list along with the seperator
        in="${in#$currentelement:}"
        if [ ! ${currentelement%%~*} ]; then # Workaround for ~ not passing as the home directory when this function is used elsewhere
            echo "$HOME${currentelement#~*}"
        else
            # Print the current element
            echo "$currentelement"
        fi
    done
}

getpathdirs