#!/bin/sh
# Function to add a given directory to the end of the path variable 
append_path() {
    case ":$PATH:" in
    *:"$1":*) ;;
    *)
        PATH="${PATH:+$PATH:}$1"
        ;;
    esac
}
# Function to add a given directory to the beginning of the path variable 
prepend_path() {
    case ":$PATH:" in
    *:"$1":*) ;;
    *)
        PATH="$1:${PATH:+$PATH}"
        ;;
    esac
}
remove_path() {
    newpath=""
    # Read through the split path variable (generated by getpathdirs)
    getpathdirs | while IFS= read -r directory; do
        # If the directory still exists after the chosen path has been excluded, then add it back to the path
        if [ "${directory%$1}" ]; then
            newpath="$newpath$directory:"
        fi
    done
    PATH=${newpath%:}
}
getpathdirs() {
    in="$PATH"
    while [ "$in" != "$currentelement" ]; do
        # Extract the first path (all text up to the first colon)
        currentelement=${in%%:*}
        # Delete the pulled path from the list along with the seperator
        in="${in#$currentelement:}"
        if [ ! ${currentelement%%~*} ]; then # Workaround for ~ not passing as the home directory when this function is used elsewhere
            echo "$HOME${currentelement#~*}"
        else
            # Print the current element
            echo "$currentelement"
        fi
    done
}
trim_filepath() {
    echo "${1##*/}"
}
