#!/bin/sh
# Utility to trim a path to only its last element
trimpath() {
    if [ "${1#"${1%?}"}" = "/" ]; then
        tmp=$(echo "$1" | sed 's/.$//')
        echo "${tmp##*/}"
    else
        echo "${1##*/}"
    fi
}

trimpath "$1"