#!/bin/sh
screenshot() {
    filename="$HOME/Pictures/Screenshots/screenshot-$(date +\%Y\%m\%d\%H\%M).png"
    if [ $XDG_SESSION_TYPE = "wayland" ]; then
        echo "This script is incompatible with a Wayland environment, aborting..."
        return 1
    else # assume an Xorg environment as a safe option if Wayland not detected
        if command -v scrot >/dev/null; then
            scrot -s "$filename"
        else
            echo "This script requires the scrot screenshot utility to function, aborting..."
            return 1
        fi
    fi
    # Preview captured screenshot in kitty terminal
    if [ $TERM = "xterm-kitty" ]; then
        kitty +kitten icat "$filename"
    else
        selection="n"
        if command -v bemenu >/dev/null; then
            selection=$(printf "No\nYes" | bemenu -p "Show image preview? [y/N]")
        elif command -v dmenu >/dev/null; then
            selection=$(printf "No\nYes" | dmenu -p "Show image preview? [y/N]")
        else
            echo "Show image preview? [y/N] "
            read selection
        fi
        selection=$(echo "$selection" | cut -c1-1)                  # Cut input to first character
        selection=$(echo "$selection" | awk '{print tolower($0)}') # Force lowercase
        if [ "$selection" = "y" ]; then
            if command -v xdg-open >/dev/null; then
                xdg-open "$filename" &
            elif command -v imv >/dev/null; then
                imv "$filename" &
            elif command -v feh >/dev/null; then
                feh "$filename" &
            else
                echo "Cannot find application to open preview with!"
            fi
        fi
    fi
    echo "Image saved to $filename"
    selection="n"
    if command -v bemenu >/dev/null; then
        selection=$(printf "No\nYes" | bemenu -p "Copy to clipboard? [y/N]")
    elif command -v dmenu >/dev/null; then
        selection=$(printf "No\nYes" | dmenu -p "Copy to clipboard? [y/N]")
    else
        printf "Copy to clipboard? [y/N] "
        read selection
    fi
    selection=$(echo "$selection" | cut -c1-1)                  # Cut input to first character
    selection=$(echo "$selection" | awk '{print tolower($0)}') # Force lowercase
    if [ "$selection" = "y" ]; then
        if [ "$XDG_SESSION_TYPE" = "wayland" ] && command -v wl-copy >/dev/null; then
            wl-copy <"$filename"
            echo "Image copied to clipboard."
        elif command -v xclip >/dev/null; then # assume an Xorg environment as a safe option if Wayland not detected
            xclip -i <"$filename"
            echo "Image copied to clipboard."
        else
            echo "Found no suitable tools with which to add to clipboard."
        fi
    fi
}

screenshot